name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  check-mixed-changesets:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm i -g pnpm@7.1.9
      - run: pnpm install --frozen-lockfile --filter="usedapp"
      - run: pnpm changeset status
      - run: pnpm changeset version
