name: Release

on:
  push:
    branches:
      - master
      - yivlad/debug-release-job

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          # This allows the changesets/action step to override the default actions user,
          # and allow CI jobs on commits coming from that step.
          persist-credentials: false

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - name: Install package manager
        run: npm i -g pnpm@7.1.9

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Print git status
        run: git status

      - name: Set git user
        run: |
          git config user.name truefibot
          git config user.email truebot.github@trusttoken.com
